#!/bin/bash
#-----------------------------------------------------------------------
# Command line interface for the Metadata Quality Assessment Framework -
#-----------------------------------------------------------------------
export VERSION=0.9.4
java -jar $(dirname $(readlink -f $0))/metadata-qa-api-${VERSION}-shaded.jar $@
