#!/bin/bash
#-----------------------------------------------------------------------
# Command line interface for the Metadata Quality Assessment Framework -
#-----------------------------------------------------------------------
export VERSION=0.9.0
java -jar $(dirname $(readlink -f $0))/target/metadata-qa-api-${VERSION}-shaded.jar $@